import { createRouter, createWebHistory } from 'vue-router'

export const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/', redirect: '/dashboard' },
    { path: '/dashboard', component: () => import('../pages/dashboard/DashboardPage.vue') },
    { path: '/stocks/list', component: () => import('../pages/stocks/StocksListPage.vue') },
    { path: '/stocks/scores', component: () => import('../pages/stocks/StockScoresPage.vue') },
    { path: '/stocks/detail/:tsCode?', component: () => import('../pages/stocks/StockDetailPage.vue'), props: true },
    { path: '/stocks/prices', component: () => import('../pages/stocks/PricesPage.vue') },
    { path: '/stocks/minline', redirect: '/stocks/prices' },
    { path: '/macro', component: () => import('../pages/macro/MacroPage.vue') },
    { path: '/intelligence/global-news', component: () => import('../pages/intelligence/GlobalNewsPage.vue') },
    { path: '/intelligence/cn-news', component: () => import('../pages/intelligence/CnNewsPage.vue') },
    { path: '/intelligence/stock-news', component: () => import('../pages/intelligence/StockNewsPage.vue') },
    { path: '/intelligence/daily-summaries', component: () => import('../pages/intelligence/DailySummariesPage.vue') },
    { path: '/signals/overview', component: () => import('../pages/signals/SignalsOverviewPage.vue') },
    { path: '/signals/themes', component: () => import('../pages/signals/ThemesPage.vue') },
    { path: '/signals/timeline', component: () => import('../pages/signals/SignalTimelinePage.vue') },
    { path: '/signals/audit', component: () => import('../pages/signals/SignalAuditPage.vue') },
    { path: '/signals/quality-config', component: () => import('../pages/signals/SignalQualityConfigPage.vue') },
    { path: '/signals/state-timeline', component: () => import('../pages/signals/SignalStateTimelinePage.vue') },
    { path: '/research/reports', component: () => import('../pages/research/ReportsPage.vue') },
    { path: '/research/multi-role', component: () => import('../pages/research/MultiRoleResearchPage.vue') },
    { path: '/research/trend', component: () => import('../pages/research/TrendAnalysisPage.vue') },
    { path: '/chatrooms/overview', component: () => import('../pages/chatrooms/ChatroomsOverviewPage.vue') },
    { path: '/chatrooms/candidates', component: () => import('../pages/chatrooms/ChatroomCandidatesPage.vue') },
    { path: '/chatrooms/chatlog', component: () => import('../pages/chatrooms/ChatlogPage.vue') },
    { path: '/chatrooms/investment', component: () => import('../pages/chatrooms/ChatroomInvestmentPage.vue') },
    { path: '/system/source-monitor', component: () => import('../pages/system/SourceMonitorPage.vue') },
    { path: '/system/database-audit', component: () => import('../pages/system/DatabaseAuditPage.vue') },
    { path: '/:pathMatch(.*)*', redirect: '/dashboard' },
  ],
})
